88 new icons
neontribe/contemplating-action pull request #101
Opened 2019-03-21 15:13 UTC by HedgehogHolly

Fixes #88 

## Description

- Added new icons

🐧

2019-03-21 22:43 UTC, katjam commented on src/styles/icons.css
> +  src:  url('fonts/info-icons.eot');
We should probably keep the comments

2019-03-21 22:44 UTC, katjam requested changes
I'd like to keep the comments in the css file for the font formats - for future us to be reminded.

2019-03-22 09:25 UTC, HedgehogHolly commented
I don't remember removing them but I might of done when I copy and pasted them.  I've added them back in @katjam

2019-03-22 09:26 UTC, katjam commented on src/styles/icons.css
> +  src:  url('fonts/info-icons.eot') format('embedded-opentype'), /* IE9 */
This ie9 comment should be on the line above

2019-03-22 09:30 UTC, katjam approved these changes
I'm not sure if the embedded font one is necessary or ie9 related (would have to look up)  - but happy to go with this.

2019-03-22 09:31 UTC, merged