1.0/183 cookie banner
neontribe/contemplating-action pull request #208
Opened 2019-08-14 14:09 UTC by Nikomus

Fixes #

## Description

- Adds a banner with some styling in the layout
- The buttons update a consent flag on the model
- Needs to check the flag before confirming GA events

@neontribe/contemplating-action

2019-08-14 18:11 UTC, katjam approved these changes
This looks great. :open_umbrella:

2019-08-15 14:36 UTC, katjam requested changes
Looks reasonable but you need to get rid of the contact keys.

Also thoughts aound if 0 and 2 mean the same thing - can we simplify?

2019-08-15 14:36 UTC, katjam commented on src/Copy/Keys.elm
> +    | ContactLinkLong
These contact ones have gone.

2019-08-15 14:36 UTC, katjam commented on src/styles/layout.scss
> +/* ------------------------------
Assuming this is good for all viewport sizes?

2019-08-15 14:40 UTC, Nikomus commented
@katjam I think I need three states for showing the banner (undecided), confirmed yes and confirmed no. I could have a pair of bools for clicked/not clicked and yes/no.

2019-08-15 14:44 UTC, katjam commented
@Nikomus But you only make decisions on 1 or _

Unless I missed something.

2019-08-15 14:45 UTC, Nikomus commented on src/Copy/Keys.elm
> +    | ContactLinkLong
Weird merge, release put them back.. 🤔

2019-08-15 14:45 UTC, katjam commented
I see you have 1 _ and 0 _ maybe you need all 3. Ignore me.

2019-08-15 14:46 UTC, Nikomus commented
The other decision is on 0 or _ in Cookies.elm to display or not.

2019-08-15 14:50 UTC, katjam approved these changes
Do it. Lovely job. :lion:

2019-08-15 15:01 UTC, merged